import './globals.css'
import { Lusitana } from 'next/font/google'

const lusitana = Lusitana({ weight: "400", subsets: ["latin"] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={lusitana.className}>
        {children}
      </body>
    </html>
  )
}
