import './globals.css'
import { DotGothic16 } from 'next/font/google'
import { dotGothic } from './ui/fonts'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dotGothic.className}>{children}</body>
    </html>
  )
}
